apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: demo-api
  name: demo-api-deployment
spec: 
  replicas: 2
  revisionHistoryLimit: 0 # Default to 10 if not specified
  selector: 
    matchLabels: 
      app: demo-api
  template: 
    metadata: 
      labels: 
        app: demo-api
    spec: 
      containers: 
      - name: demo-api
        ports: 
        - containerPort: 8000
