apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api-production
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SebastianScherer88/argo-cd-k8s-config.git
    targetRevision: HEAD
    path: environments/production # location of the demo-api helm chart

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-api-production

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true