apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api-development
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SebastianScherer88/argo-cd-k8s-config.git
    targetRevision: HEAD
    path: environments/development # location of the demo-api helm chart

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-api-development

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true