apiVersion: apps/v1
kind: Deployment
metadata: 
  name: demo-api-deployment
spec:
  template: 
    spec: 
      containers: 
      - image: bettmensch88/argo-cd-demo-api:development-0f8c8bef53d632a6e036b142d9f6dfdfa8028cee