apiVersion: apps/v1
kind: Deployment
metadata: 
  name: demo-api-deployment
spec:
  template: 
    spec: 
      containers:
      - name: demo-api
        image: bettmensch88/argo-cd-demo-api:stage-a0c5e1d075e0a18a257cf2e7fabf804b9e31fee8